version: '3.8'

services:
  db:
    image: postgres:15.5
    container_name: animalsim
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=animalsim
    ports:
      - "25060:5432"