version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nest_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin167
      POSTGRES_DB: animalsim
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
